server:
  port: 8761

spring:
  application:
    name: eureka-server
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: localhost




